(library
 (name test_schnorr_proof_performance)
 (libraries
  ;; opam libraries
  ppx_inline_test.config
  core_kernel
  async
  ;; local libraries
  pickles
  random_oracle
  random_oracle_input
  signature_lib
  snark_params)
 (instrumentation
  (backend bisect_ppx))
 (inline_tests
  (flags -verbose -show-counts))
 (preprocess
  (pps ppx_inline_test ppx_version)))
